### ISSUE TITLE
Using fp16 models crash

### ISSUE THREAD

**Issue by fnando1995** [BlueMirrors/Yolov5-TensorRT#10]
Hello @makaveli10 @shivamswarnkar @aditya-dl ,

I just see a closed issue about fp32 conversion, thus I @ you at this, maybe you can help me out.

I am trying to use fp16 models, I use the conversion file of the ultralytics repo (export.py), the conversion was succesfully (for fp32 models I also use this repo). fp32 models can run with no problems for the detect.py but the fp16 models not.

This execution is inside a Jetson Nano 4gb.

UPDATE: fp32 model with input_shape = 320 give the same error in the exact same line. Somethins I can refer to, is that the first line says "Building and Optimizing TRT-Engine for input_shape=(640, 640). " even if the model is a 320 input_shape. Is this a bad convertion? I think this might be a problem in the yolov5 implementation. Maybe a bad argument parsing...

This is the traceback

```
[CVU-Info] Building and Optimizing TRT-Engine for input_shape=(640, 640). This might take a few minutes for first time.
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +198, GPU +0, now: CPU 242, GPU 2455 (MiB)
[TensorRT] INFO: Loaded engine size: 10 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 252 MiB, GPU 2466 MiB
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +158, GPU +159, now: CPU 417, GPU 2628 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +241, GPU +241, now: CPU 658, GPU 2869 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 658, GPU 2869 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine end: CPU 658 MiB, GPU 2869 MiB
[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation begin: CPU 647 MiB, GPU 2859 MiB
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 647, GPU 2859 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +1, GPU +0, now: CPU 648, GPU 2859 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation end: CPU 648 MiB, GPU 2859 MiB
Traceback (most recent call last):
  File "detect.py", line 88, in <module>
    classes="coco")
  File "detect.py", line 36, in detect_batch
    for w in range(warmup):  model(image)
  File "/usr/local/lib/python3.6/dist-packages/cvu/detector/yolov5/core.py", line 96, in __call__
    outputs = self._model(processed_inputs)
  File "/usr/local/lib/python3.6/dist-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 256, in __call__
    outputs = self._inference(inputs)
  File "/usr/local/lib/python3.6/dist-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 278, in _inference
    cuda.memcpy_htod_async(inp['device'], inp['host'], self._stream)
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid argument
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 1243, GPU 3446 (MiB)
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
test_all.sh: line 10: 11837 Aborted                 (core dumped) python3 detect.py --input ./part/ --output ./part_pred_16/ --weights weights/jn_created_16/yolov5n.engine
```

Any recommendations?

**Comment by fnando1995** [comment]
By looking at cvu code in this [line](https://github.com/BlueMirrors/cvu/blob/50b65cc0a6caa9e636804d3ce10a3ee611b44cd8/cvu/detector/yolov5/core.py#L69) where preprocesses are added to yolov5 class, the letterbox is sent with no modifications in the arguments, and the defaults are used [here](https://github.com/BlueMirrors/cvu/blob/50b65cc0a6caa9e636804d3ce10a3ee611b44cd8/cvu/preprocess/image/letterbox.py#L11), I will change this and retry.

**Comment by shivamswarnkar** [comment]
Hi @fnando1995, you're right that the ```letterbox``` gets the default arguments. And it's because the ```TensorRT engine``` is not actually built for the ```input shapes``` you provide, but rather for the ```input shapes``` that comes out after the entire ```preprocess``` (including ```letterboxing```).  Sorry for this confusion.

```
img-size [320x320] --> letterbox (assuming scaleup is True)--> [640, 640] --> TensorRT Engine
```
Just for clarification, the output shape of the ```letterbox``` depends on the input image-size.

If you want to build/use the engine specifically for any certain input size, then you have already found the solution (i.e. change the defaults args in the ```letterbox```, or remove the ```letterbox``` altogether [here](https://github.com/BlueMirrors/cvu/blob/50b65cc0a6caa9e636804d3ce10a3ee611b44cd8/cvu/detector/yolov5/core.py#L69)). However, if this doesn't solve the issue you're facing, then please let us know and we'll try to test it on our end.

We are planning to make all the yolov5 parameters (e.g. args for ```letterbox```, ```scale```, ```NMS``` etc.) optionally available, but that might take some time.

**Comment by shivamswarnkar** [comment]
@fnando1995 closing issue for now. Feel free to reopen it if needed.
