### ISSUE TITLE
How can I choose the yolov5m weights and the size of the image when running detect.py?

### ISSUE THREAD

**Issue by RoyCopter** [BlueMirrors/Yolov5-TensorRT#13]
hey,
How can I choose the yolov5m weights and the size of the image when running detect.py?

thanks

**Comment by shivamswarnkar** [comment]
Hi, @RoyCopter,

```yolov5m``` is not given by default (only ```yolov5s``` is given). You can get the ```yolov5m``` pre-trained weights from Ultralytics official Yolov5 repo (you'll have to use their ```export.py``` to convert ```.pt``` weights to ```.onnx```, more info [here](https://github.com/ultralytics/yolov5/issues/251)). Once you have the ```.onnx``` weights, you can use them by simply providing ```--weights``` flag in our ```detect.py```. 

As for ```image-size```, you can use flag like this ```--img-size 720 1080```. Do remember, this is the image size before preprocessing, and your ```TensorRT``` engine is generated for input-shape after preprocessing which can be different. More info [here](https://github.com/BlueMirrors/Yolov5-TensorRT/issues/10#issuecomment-1045304965)
