### ISSUE TITLE
ModuleNotFoundError: No module named 'cvu'

### ISSUE THREAD

**Issue by wxthu** [BlueMirrors/Yolov5-TensorRT#16]
i have finished installation according to requirement.txt but when I run detect.py I meet following error ...
![image](https://user-images.githubusercontent.com/73052387/161413754-88dc0daa-869d-47b2-8567-fe22c8826244.png)

**Comment by shivamswarnkar** [comment]
@wxthu can you run the following again and share the output

```pip install -r requirements.txt```

**Comment by wxthu** [comment]
> @wxthu can you run the following again and share the output
> 
> `pip install -r requirements.txt`

![image](https://user-images.githubusercontent.com/73052387/161461113-a97c1cea-fa6d-420a-b672-d0baba518815.png)
stuck....

**Comment by wxthu** [comment]
> @wxthu can you run the following again and share the output
> 
> `pip install -r requirements.txt`

![image](https://user-images.githubusercontent.com/73052387/161476524-9ab6884b-5e0d-4170-ac92-d5a4daad2d27.png)

**Comment by shivamswarnkar** [comment]
@wxthu you have multiple python versions that's why you're getting these errors. Pip is installing cvu for Python 3.6 while 'python' command is running Python 3.7.6. that's why you're getting ```defaulting to user installation....```. Try running ```python -m pip install -r requirements.txt``` This will install correct requirements for the correct python version.

PS avoid using "pip install cvu-python" since the deployed pip package is not upto date with cvu-python repo yet and you may get some errors

**Comment by wxthu** [comment]
> python -m pip install -r requirements.txt

Thanks for you reply and I have fixed this problem . And when I run **python detect.py --weights yolov5s.engine --input in1.jpeg --output ou2.jpeg**  I met some following errors:
![image](https://user-images.githubusercontent.com/73052387/161486071-a7ec2e0a-a8a2-4fdb-bfab-cfdae8857739.png)
As above **yolov5s.engine** is generated according to https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/README.md

**Comment by makaveli10** [comment]
Hello @wxthu, it seems there is a mismatch between the tensorrt version used to convert from ```onnx``` to ```tensorrt``` and the version which is being used to do inference.

So, its best to either uninstall ```tensorrt``` and use the ```auto_install``` option that the script has which should eradicate this issue. Or you could make sure that you use the same tensorrt version to convert from onnx to tensorrt and inference.

**Comment by wxthu** [comment]
> Hello @wxthu, it seems there is a mismatch between the tensorrt version used to convert from `onnx` to `tensorrt` and the version which is being used to do inference.
> 
> So, its best to either uninstall `tensorrt` and use the `auto_install` option that the script has which should eradicate this issue. Or you could make sure that you use the same tensorrt version to convert from onnx to tensorrt and inference.

I am sure that only version tensorrt was installed on my machine
<img width="827" alt="image" src="https://user-images.githubusercontent.com/73052387/161571807-b086c0be-8a93-4095-a012-868ee08db911.png">

**Comment by makaveli10** [comment]
Interesting. Let me try and reproduce this on my end. So can you mention the steps you followed?

**Comment by wxthu** [comment]
> Interesting. Let me try and reproduce this on my end. So can you mention the steps you followed?

I download the **yolov5s.pt** file from  official website https://github.com/ultralytics/yolov5 and convert it to yolov5s.engine according to https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/README.md, then I run above command in this repo and meet these errors
BTW:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/73052387/161574830-7669b1c4-02b2-4ca7-98fb-c2d00b285b36.png">

**Comment by makaveli10** [comment]
there you go.. you do have multiple tensorrt versions installed. So, I'd recommend to make sure you have only one installed. [Wang's repo](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5) builds engine from network definition and this repo uses onnx model, parses it and then builds the engine so, use [the conversion script](https://github.com/BlueMirrors/Yolov5-TensorRT/blob/master/convert.py) to create tensorrt engine after you have uninstalled the other tensorrt versions but the one that you would want to use.

**Comment by wxthu** [comment]
> there you go.. you do have multiple tensorrt versions installed. So, I'd recommend to make sure you have only one installed. [Wang's repo](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5) builds engine from network definition and this repo uses onnx model, parses it and then builds the engine so, use [the conversion script](https://github.com/BlueMirrors/Yolov5-TensorRT/blob/master/convert.py) to create tensorrt engine after you have uninstalled the other tensorrt versions but the one that you would want to use.

I have solved that and thanks so much!
