### ISSUE TITLE
unexpected keyword argument 'auto_install'

### ISSUE THREAD

**Issue by MrRace** [BlueMirrors/Yolov5-TensorRT#19]
I install cvu with `pip install cvu-python`, and when run the convert.py comes error:
```
Traceback (most recent call last):
  File "convert.py", line 72, in <module>
    convert_onnx_to_trt(opt.weights,
  File "convert.py", line 19, in convert_onnx_to_trt
    convert = Yolov5Trt(classes=list(map(str, range(nc))),
TypeError: __init__() got an unexpected keyword argument 'auto_install'
```

**Comment by shivamswarnkar** [comment]
Hi @MrRace, we haven't published latest changes in cvu-python to pypi package, thus the error. Can you please uninstall that cvu installation, and install it through ```pip install -r requirements.txt``` (this will install cvu-python directly from GitHub repository)
