### ISSUE TITLE
ValueError: cannot reshape array of size 151200 into shape (1,newaxis,85)

### ISSUE THREAD

**Issue by B-RJ** [BlueMirrors/Yolov5-TensorRT#2]
First of all, thank you for your work

I'm getting the error above after running `convert.py` with a retrained model with 3 classes.

For exporting to onnx I used:
`python export.py --weights best.pt --dynamic --include onnx`

Then I ran:
`python convert.py --weights best.onnx --nc 3 --img-size 480 640`

What could I do to fix the issue?

Thanks in advance for your help :)

**Comment by shivamswarnkar** [comment]
Hi @B-RJ 

This is an issue on our side. We only gave support for coco classes in the first release. But we're going to push new update in just a few hours that should fix this issue. I'll update you once the update is online.

Thanks and sorry for this inconvenience.

**Comment by shivamswarnkar** [comment]
Hi @B-RJ 

We have pushed the updates. Can you check if your issue still persists?

**Comment by B-RJ** [comment]
Hey 

I'm getting the same error.

**Comment by shivamswarnkar** [comment]
Are you doing it in your local system? In that case, you might need to uninstall cvu-python

**Comment by B-RJ** [comment]
Yes, in my local system. I'll do that

**Comment by shivamswarnkar** [comment]
And also try running the pip install -r requirements again (we are now directly installing from cvu-python repo to reflect changes quickly, we'll change to pip package once we release the stable version by the end of the month).

**Comment by B-RJ** [comment]
Thank you very much @shivamswarnkar. It works now

**Comment by B-RJ** [comment]
:)

**Comment by shivamswarnkar** [comment]
awesome, glad it worked XD.  I'll close the issue now, thanks for bringing it up!
