### ISSUE TITLE
Can we infer the custom yolov5 weights on CSI camera?

### ISSUE THREAD

**Issue by Rusali28** [BlueMirrors/Yolov5-TensorRT#24]
Hello,
I have generated my own weights file and also converted it to TensorRT engine. But I can't figure out how to infer it using a CSI camera, can you please help?

**Comment by Hyrtsi** [comment]
@Rusali28 you have to write the driver for the camera to get the image to memory. It's not in the scope of this repository. Maybe you can google some code examples for your camera model.

Simply load the image to a numpy array. Figure out the color space and channel order properly and pass it to the NN.

If you post your camera model I can help further. But I think this issue should be closed as off topic.

**Comment by makaveli10** [comment]
Thanks @Hyrtsi
