### ISSUE TITLE
Autoinstalling pycuda fails

### ISSUE THREAD

**Issue by batrlatom** [BlueMirrors/Yolov5-TensorRT#3]
Hello,
I am evaluating your submission for yolov5 export competition, but I have a problem with the conversion.
My hardware is jetson nano 4GB with jetpack 4.5.1, clean installation. I already have tensrrt and pycuda on the system installed. Could you please help me to make it ork so I can evaluate it properly? Thanks

```
[CVU-Info] Auto-Installing pycuda...
  Failed building wheel for pycuda
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tzftah6j/pycuda/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tnvqcq0p-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-tzftah6j/pycuda/
[CVU-Error] Pycuda Auto-Installation Failed...
[CVU-Info] Auto-Installing nvidia-tensorrt...
  Could not find a version that satisfies the requirement nvidia-tensorrt (from versions: )
No matching distribution found for nvidia-tensorrt
[CVU-Error] Nvidia-Tensorrt Auto-Installation Failed...
[CVU-Error] Nvidia-Tensorrt Import Failed, either change backend or reinstall it properly...
Segmentation fault (core dumped)
```

**Comment by shivamswarnkar** [comment]
Hi @batrlatom, 

It only attempts to auto-install when it can't import pycuda and tensorrt (we have tested that on multiple devices and configurations including jetson devices),  so I'm not sure why this is happening. 

You can try to manually turn off the auto-install feature to see if it's able to properly import tensorrt and pycuda as expected. You can simply use ```--no-auto-install``` flag when running convert.py or detect.py ( I have added this new flag for your convenience, so reclone or do a git pull). And I would also recommend running with a new clean environment or at least reinstall the requirements.txt for stability.

Thank you for your time, and sorry for this trouble!

**Comment by batrlatom** [comment]
Thanks for the answer, i Will try to turn off autoinstall and test it later today. Best

**Comment by shivamswarnkar** [comment]
Hi @batrlatom , were you able to solve this issue? If yes then can I close this issue?

**Comment by shivamswarnkar** [comment]
I assume this issue is no longer relevant, so I'll close it for now. Feel free to open it again if something changes
