### ISSUE TITLE
FP32 TensorRT conversion

### ISSUE THREAD

**Issue by makaveli10** [BlueMirrors/Yolov5-TensorRT#5]
@shivamswarnkar, Thanks for writing the tensorRT conversion and inference script. However, when I convert the model to fp16 it reduces the accuracy. Is there any configuration so that I convert the model to tensorRT but does not need to change the precision to fp16 and convert the model with fp32. Thank you

_Originally posted by @rashmi-learning in https://github.com/BlueMirrors/Yolov5-TensorRT/issues/4#issuecomment-1027625022_

**Comment by makaveli10** [comment]
@rashmi-learning while testing on our end we had minimal to no performance loss in FP16 precesion. We believe that this observation should persist.

So, we have some queries to understand the issue:
- can you give us some more details on how bad of performance loss you observed ?
- what yolov5 model you used? 
- how did you convert your yolov5 model to onnx?

**Comment by rashmi-learning** [comment]
@shivamswarnkar, Thanks for writing back.
So, I am performing the conversion for custom classes trained model. For that purpose 
-    we are using, YOLOv5n and YOLOv5s model.
- TO convert the .pt weights to .onnx, we are using the YOLOv5 repository conversion method using export.py https://github.com/ultralytics/yolov5.git 
- As we are training our model for small objects, the accuracy drops from 95% to almost 70-75%. 
- As we don't want any drop in accuracy, is there any way we can convert the TensorRT model with fp32 precision. Any help will be highly appreciated. Thank You

**Comment by makaveli10** [comment]
@rashmi-learning Please update your Yolov5-TensorRT repo and re-install the requirements. We have added the feature to create fp32 precision tensorrt engine.
After updating the repo and re-installing requirements, use the below command to create fp32 model:

```python3 convert.py --fp32```

**Comment by rashmi-learning** [comment]
@makaveli10, @shivamswarnkar Thanks for adding the feature for converting model with f32 precision.

**Comment by shivamswarnkar** [comment]
@rashmi-learning Thank you for trying out our work! Feel free to reopen this issue if it isn't resolved for you.
