### ISSUE TITLE
YOLOv5 Release Version

### ISSUE THREAD

**Issue by rwin94** [BlueMirrors/Yolov5-TensorRT#7]
Hi, which YOLOv5 version are you using for the original yolov5s.pt weights? Is it the latest... https://github.com/ultralytics/yolov5/releases/tag/v6.0? Thanks!

**Comment by shivamswarnkar** [comment]
Hi @rwin94, default weights are from [v5.0](https://github.com/ultralytics/yolov5/releases/tag/v5.0).

I think [v6.0](https://github.com/ultralytics/yolov5/releases/tag/v6.0) weights should also work with our code, but we haven't really tried it yet.
