### ISSUE TITLE
Reproduce repo in jetson nano 4gb

### ISSUE THREAD

**Issue by fnando1995** [BlueMirrors/Yolov5-TensorRT#9]
Hello, just use this repo for doing inferences in a laptop with nvidia-gtx1650, thus I want to reproduce it in a jetson nano of 4GB. Is this repo able to being reproduced in a Jetson Nano? I have been troubled with nvidia-tensorrt instalation (False to auto_install option) but keep having this problem: 

Note: made some changes in args to use a folder instead of an image or video, but this works in the laptop.

```
$ python3 detect.py --input ./set_images/ --output ./set_images_pred/ --weights weights/yolov5n.engine
[CVU-Info] Auto-Installing pycuda...
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/heatmap/.local/lib/python3.6'
Check the permissions.

[CVU-Error] Pycuda Auto-Installation Failed...
[CVU-Info] Auto-Installing nvidia-tensorrt...
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
ERROR: Could not find a version that satisfies the requirement nvidia-tensorrt (from versions: none)
ERROR: No matching distribution found for nvidia-tensorrt
[CVU-Error] Nvidia-Tensorrt Auto-Installation Failed...
[CVU-Error] Nvidia-Tensorrt Import Failed, either change backend or reinstall it properly...
[CVU-Info] Building and Optimizing TRT-Engine for input_shape=(640, 640). This might take a few minutes for first time.
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +198, GPU +0, now: CPU 242, GPU 2861 (MiB)
[TensorRT] INFO: Loaded engine size: 11 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 254 MiB, GPU 2873 MiB
[TensorRT] ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::34] Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 43, Serialized Engine Version: 0)
[TensorRT] ERROR: 4: [runtime.cpp::deserializeCudaEngine::76] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "detect.py", line 167, in <module>
    auto_install=False)
  File "detect.py", line 112, in detect_batch
    preds = model(image)
  File "/usr/local/lib/python3.6/dist-packages/cvu/detector/yolov5/core.py", line 96, in __call__
    outputs = self._model(processed_inputs)
  File "/usr/local/lib/python3.6/dist-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 244, in __call__
    self._load_model(self._weight)
  File "/usr/local/lib/python3.6/dist-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 129, in _load_model
    raise Exception("[CVU-Error] Couldn't build engine successfully !")
Exception: [CVU-Error] Couldn't build engine successfully !
```

As jetson nano's Jetpack comes with tensorrt, I did not install nvidia-tensorrt, but pyindex and pycuda where installed in the jetson nano (made me work for it but already done).

The engines are the same as in the laptop, passed by ftp.

Hope anyone could give me a clue.

**Comment by shivamswarnkar** [comment]
Hi @fnando1995, have you tried running with ```--no-auto-install``` flag?

I think this is a similar issue #3

**Comment by fnando1995** [comment]
@shivamswarnkar hello!
I just put False on auto_install Flag in the code directly. In the jetson nano 4gb I have seen that problem before, it works around with:

`export OPENBLAS_CORETYPE=ARMV8`

I supposed that the problem might be a problem with the engine compilation, as In my laptop tensorrt's version in 8.0.2 and in the Nano is 8.0.0,, So now I am compiling using export.py from ultralitycs yolov5 repo. Hope this works, since I can tell that the problem is a deserialization fron tensorrt...

**Comment by fnando1995** [comment]
> @shivamswarnkar hello! I just put False on auto_install Flag in the code directly. In the jetson nano 4gb I have seen that problem before, it works around with:
> 
> `export OPENBLAS_CORETYPE=ARMV8`
> 
> I supposed that the problem might be a problem with the engine compilation, as In my laptop tensorrt's version in 8.0.2 and in the Nano is 8.0.0,, So now I am compiling using export.py from ultralitycs yolov5 repo. Hope this works, since I can tell that the problem is a deserialization fron tensorrt...

yeap, was that. After exporting .pt models to .engine in the jetson nano, the deserialization worked, and it started to infere!
